import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const dm_sans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dm_sans.className}>
        <div className="max-w-7xl mx-auto flex justify-between items-center mb-10 md:py-2 p-2">
          <Link href={"/"}>
            <Image
              width={300}
              height={500}
              className="md:w-32 w-20"
              src={"https://olmaliqbmsm.uz/img/8_MBSM_Logo.jpg"}
              alt=""
            />
          </Link>
          <div>
            <h1 className="text-center md:font-bold font-semibold md:text-xl text-xs">
              TOSHKENT VILOYATI OLMALIQ SHAHAR 8-SONLI BOLALAR MUSIQA VA
              SAN&apos;AT MAKTABI
            </h1>
            <p className="text-center md:block hidden font-medium  md:text-base text-xs">
              Olmaliq shahar Amir Tumur ko&apos;chasi 51-uy <br /> Tel.: +998
              70-614-27-17
            </p>
          </div>

          <button className="w-36 md:block hidden bg-blue-600 text-white h-10 rounded-lg font-medium">
            Telegram
          </button>
        </div>
        {children}
      </body>
    </html>
  );
}
